name: mil_abbr
description: A clean military abbreviation search app with Favorites and PDF export.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  url_launcher: ^6.2.5
  pdf: ^3.10.1
  printing: ^5.11.0
  path_provider: ^2.0.15
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/abbreviations.json